FROM ubuntu/apache2:latest

COPY apache2.conf /etc/apache2
COPY 000-default.conf /etc/apache2/sites-enabled/

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install iputils-ping -y

RUN a2enmod proxy proxy_http proxy_connect rewrite ssl proxy_html headers


RUN service apache2 restart

EXPOSE 80/tcp